import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const baseConfigPath = "wrangler.toml";
const productionId = process.env.CONFIG_KV_NAMESPACE_ID?.trim();
const previewId = process.env.CONFIG_KV_PREVIEW_NAMESPACE_ID?.trim() || productionId;
const baseConfigForDetection = readFileSync(baseConfigPath, "utf8")
  .split("\n")
  .filter((line) => !line.trimStart().startsWith("#"))
  .join("\n");
const hasInlineKvBinding = /\[\[kv_namespaces\]\][\s\S]*?binding\s*=\s*["']CONFIG_KV["']/.test(
  baseConfigForDetection,
);

const args = ["wrangler", "deploy"];

if (productionId && !hasInlineKvBinding) {
  const generatedDir = mkdtempSync(join(tmpdir(), "auto-email-wrangler-"));
  const generatedConfigPath = join(generatedDir, "wrangler.toml");
  const baseConfig = readFileSync(baseConfigPath, "utf8").trimEnd();
  const kvConfig = [
    "",
    "# Generated by scripts/deploy.mjs from CONFIG_KV_NAMESPACE_ID.",
    "[[kv_namespaces]]",
    'binding = "CONFIG_KV"',
    `id = "${productionId}"`,
    `preview_id = "${previewId}"`,
    "",
  ].join("\n");

  writeFileSync(generatedConfigPath, `${baseConfig}\n${kvConfig}`);
  args.push("--config", generatedConfigPath);
  console.log("Using CONFIG_KV binding from CONFIG_KV_NAMESPACE_ID for this deployment.");
} else if (!hasInlineKvBinding) {
  console.warn(
    "CONFIG_KV_NAMESPACE_ID is not set and wrangler.toml does not declare CONFIG_KV. " +
      "This deployment may not include the KV binding.",
  );
}

const result = spawnSync("npx", args, { stdio: "inherit", shell: process.platform === "win32" });
process.exit(result.status ?? 1);
